### ISSUE TITLE
Icons smaller than JUMBO are cropped.

### ISSUE THREAD

**Issue by TX256** [MrMarnic/JIconExtract#1]
For me, on Windows 10, icons smaller than JUMBO are cropped a bit from right and bottom.

**Comment by MrMarnic** [comment]
The issue is known and I am working on it but I cannot tell you an specific date

**Comment by MrMarnic** [comment]
Sorry for the big delay. But I managed it only now to fix this problem.
It is fixed in the new project https://github.com/MrMarnic/JIconExtractReloaded.
